dist: trusty
sudo: false
language: ruby
rvm:
  - '2.4'
  - '2.3'
  - '2.2'
  - '2.1'
  - '2.0'
  - '1.9.3'
  - jruby-9.1.9.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
addons:
  code_climate:
    repo_token:
      secure: DNXX6vrtb1D1NSxA22LTgHAnIEiRt5OJ6sYeakj3tdtOwclA9/dT+mYA8zI+l8uI7d0ojdWGlWWoJKbLsVvebDaoYSVm7ekLBMS3dhQ/gvd5RIZ0Eo6xadB0QMfsTXIhCkFt8CNlL0YI89abyhLSX2Vn8QFN7K5ihbkKatR+2JY=
